services:
  postgres:
    image: postgres:16
    container_name: postgres-db-mahika
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mahika@123
      POSTGRES_DB: mahika_website
      TZ: "UTC"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  redis:
    image: redis:7
    container_name: redis-mahika
    restart: always
    environment:
      TZ: "UTC"
    ports:
      - '6380:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-backend
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_FAMILY: ${REDIS_FAMILY}
    depends_on:
      - postgres
      - redis
    ports:
      - '3002:3001'
    command: ['npm', 'run', 'start:prod']

volumes:
  pgdata:
